project "FluentCassandra"
    category "_Libraries"
    kind "SharedLib"
    language "C#"

    linksystemlibs {
        "System",
        "System.Core",
        "System.Xml",
    }

    compilefiles {
        "upstream/src/Configuration/CassandraConfiguration.cs",
        "upstream/src/Configuration/CassandraConfigurationContainer.cs",
        "upstream/src/Configuration/CassandraConfigurationMap.cs",
        "upstream/src/Configuration/CassandraTypeConfiguration.cs",
        "upstream/src/Configuration/ICassandraConfigurationMap.cs",
        "upstream/src/Configuration/IConfigurationContainer.cs",
        "upstream/src/Configuration/IKeyGetMapping.cs",
        "upstream/src/Configuration/IKeyMapping.cs",
        "upstream/src/Configuration/IKeySetMapping.cs",
        "upstream/src/Configuration/IPropertyGetMapping.cs",
        "upstream/src/Configuration/IPropertyMapping.cs",
        "upstream/src/Configuration/IPropertySetMapping.cs",
        "upstream/src/Configuration/ITypeConfiguration.cs",
        "upstream/src/Configuration/ITypeGetConfiguration.cs",
        "upstream/src/Configuration/ITypeSetConfiguration.cs",
        "upstream/src/Configuration/KeyMappingExpression.cs",
        "upstream/src/Configuration/PropertyMappingExpression.cs",
        "upstream/src/Connections/Connection.cs",
        "upstream/src/Connections/ConnectionBuilder.cs",
        "upstream/src/Connections/ConnectionProvider.cs",
        "upstream/src/Connections/ConnectionProviderFactory.cs",
        "upstream/src/Connections/IConnection.cs",
        "upstream/src/Connections/IConnectionProvider.cs",
        "upstream/src/Connections/IServerManager.cs",
        "upstream/src/Connections/NormalConnectionProvider.cs",
        "upstream/src/Connections/PooledConnectionProvider.cs",
        "upstream/src/Connections/RoundRobinServerManager.cs",
        "upstream/src/Connections/Server.cs",
        "upstream/src/Connections/TimedLock.cs",
        "upstream/src/Operations/BatchMutate.cs",
        "upstream/src/Operations/CassandraIndexClause.cs",
        "upstream/src/Operations/CassandraIndexClauseBuilder.cs",
        "upstream/src/Operations/CassandraKeyRange.cs",
        "upstream/src/Operations/CassandraOperationEnlistment.cs",
        "upstream/src/Operations/CassandraQuerySetup.cs",
        "upstream/src/Operations/CassandraQueryable.cs",
        "upstream/src/Operations/CassandraSlicePredicate.cs",
        "upstream/src/Operations/CassandraSlicePredicateBuilder.cs",
        "upstream/src/Operations/CassandraSlicePredicateQuery.cs",
        "upstream/src/Operations/ColumnCount.cs",
        "upstream/src/Operations/ColumnFamilyOperation.cs",
        "upstream/src/Operations/ColumnSlicePredicate.cs",
        "upstream/src/Operations/ContextOperation.cs",
        "upstream/src/Operations/GetColumn.cs",
        "upstream/src/Operations/GetColumnFamilyIndexedSlices.cs",
        "upstream/src/Operations/GetColumnFamilyRangeSlices.cs",
        "upstream/src/Operations/GetColumnFamilySlice.cs",
        "upstream/src/Operations/GetSuperColumn.cs",
        "upstream/src/Operations/GetSuperColumnFamilyIndexedSlices.cs",
        "upstream/src/Operations/GetSuperColumnFamilyRangeSlices.cs",
        "upstream/src/Operations/GetSuperColumnFamilySlice.cs",
        "upstream/src/Operations/GetSuperColumnIndexedSlices.cs",
        "upstream/src/Operations/GetSuperColumnRangeSlices.cs",
        "upstream/src/Operations/GetSuperColumnSlice.cs",
        "upstream/src/Operations/Helper.cs",
        "upstream/src/Operations/ICassandraQueryProvider.cs",
        "upstream/src/Operations/ICassandraQueryable.cs",
        "upstream/src/Operations/InsertColumn.cs",
        "upstream/src/Operations/MultiGetColumnCount.cs",
        "upstream/src/Operations/MultiGetColumnFamilySlice.cs",
        "upstream/src/Operations/MultiGetSuperColumnFamilySlice.cs",
        "upstream/src/Operations/MultiGetSuperColumnSlice.cs",
        "upstream/src/Operations/QueryableColumnFamilyOperation.cs",
        "upstream/src/Operations/RangeSlicePredicate.cs",
        "upstream/src/Operations/RemoveColumn.cs",
        "upstream/src/Operations/RemoveKey.cs",
        "upstream/src/Operations/RemoveSuperColumn.cs",
        "upstream/src/Operations/Truncate.cs",
        "upstream/src/Operations/Void.cs",
        "upstream/src/Properties/AssemblyInfo.cs",
        "upstream/src/Thrift/TApplicationException.cs",
        "upstream/src/Thrift/TProcessor.cs",
        "upstream/src/Types/AsciiType.cs",
        "upstream/src/Types/AsciiTypeConverter.cs",
        "upstream/src/Types/BytesType.cs",
        "upstream/src/Types/BytesTypeConverter.cs",
        "upstream/src/Types/CassandraConversionHelper.cs",
        "upstream/src/Types/CassandraType.cs",
        "upstream/src/Types/IntegerType.cs",
        "upstream/src/Types/IntegerTypeConverter.cs",
        "upstream/src/Types/LexicalUUIDType.cs",
        "upstream/src/Types/LexicalUUIDTypeConverter.cs",
        "upstream/src/Types/LongType.cs",
        "upstream/src/Types/LongTypeConverter.cs",
        "upstream/src/Types/NullType.cs",
        "upstream/src/Types/TimeUUIDType.cs",
        "upstream/src/Types/TimeUUIDTypeConverter.cs",
        "upstream/src/Types/UTF8Type.cs",
        "upstream/src/Types/UTF8TypeConverter.cs",
        "upstream/src/Types/VoidType.cs",
    }

done "FluentCassandra"
